const menuData = {
  Menus: [
    {
      title: "Family Feast",
      image: "assets/images/family_feast.jpg",
      description: "A large meal perfect for the whole family.",
      price: 29.99,
    },
    {
      title: "Couple's Combo",
      image: "assets/images/couples_combo.jpg",
      description: "A meal for two with a variety of items.",
      price: 19.99,
    },
    {
      title: "Kids Meal",
      image: "assets/images/kids_meal.jpg",
      description: "A fun and tasty meal for kids.",
      price: 9.99,
    },
    {
      title: "Vegetarian Delight",
      image: "assets/images/vegetarian_delight.jpg",
      description: "A healthy and delicious vegetarian meal.",
      price: 14.99,
    },
    {
      title: "Seafood Special",
      image: "assets/images/seafood_special.jpg",
      description: "A meal featuring a variety of seafood.",
      price: 24.99,
    },
    {
      title: "Chicken Lovers",
      image: "assets/images/chicken_lovers.jpg",
      description: "A meal for those who love chicken.",
      price: 19.99,
    },
    {
      title: "Beef Bonanza",
      image: "assets/images/beef_bonanza.jpg",
      description: "A hearty meal with a variety of beef dishes.",
      price: 22.99,
    },
    {
      title: "Pasta Party",
      image: "assets/images/pasta_party.jpg",
      description: "A meal featuring a variety of pasta dishes.",
      price: 17.99,
    },
    {
      title: "Breakfast Bundle",
      image: "assets/images/breakfast_bundle.jpg",
      description: "A meal to start your day right.",
      price: 12.99,
    },
    {
      title: "Dessert Delight",
      image: "assets/images/dessert_delight.jpg",
      description: "A meal featuring a variety of desserts.",
      price: 15.99,
    },
  ],
  Sandwiches: [
    {
      title: "Turkey Club",
      image: "assets/images/turkey_club.jpg",
      description: "A classic turkey club sandwich.",
      price: 8.99,
    },
    {
      title: "BLT",
      image: "assets/images/blt.jpg",
      description: "Bacon, lettuce, and tomato sandwich.",
      price: 7.99,
    },
    {
      title: "Grilled Cheese",
      image: "assets/images/grilled_cheese.jpg",
      description: "A delicious grilled cheese sandwich.",
      price: 6.99,
    },
    {
      title: "Ham and Cheese",
      image: "assets/images/ham_and_cheese.jpg",
      description: "A tasty ham and cheese sandwich.",
      price: 7.99,
    },
    {
      title: "Chicken Salad",
      image: "assets/images/chicken_salad.jpg",
      description: "A fresh chicken salad sandwich.",
      price: 8.99,
    },
    {
      title: "Veggie Delight",
      image: "assets/images/veggie_delight.jpg",
      description: "A healthy veggie sandwich.",
      price: 7.99,
    },
    {
      title: "Tuna Melt",
      image: "assets/images/tuna_melt.jpg",
      description: "A warm and tasty tuna melt.",
      price: 8.99,
    },
    {
      title: "Roast Beef",
      image: "assets/images/roast_beef.jpg",
      description: "A hearty roast beef sandwich.",
      price: 9.99,
    },
    {
      title: "Meatball Sub",
      image: "assets/images/meatball_sub.jpg",
      description: "A delicious meatball sub.",
      price: 9.99,
    },
    {
      title: "Pulled Pork",
      image: "assets/images/pulled_pork.jpg",
      description: "A flavorful pulled pork sandwich.",
      price: 8.99,
    },
  ],
  Drinks: [
    {
      title: "Coca Cola",
      image: "assets/images/coca_cola.jpg",
      description: "Refreshing cola drink.",
      price: 1.99,
    },
    {
      title: "Pepsi",
      image: "assets/images/pepsi.jpg",
      description: "Popular cola drink.",
      price: 1.99,
    },
    {
      title: "Water",
      image: "assets/images/water.jpg",
      description: "Pure bottled water.",
      price: 0.99,
    },
    {
      title: "Orange Juice",
      image: "assets/images/orange_juice.jpg",
      description: "Freshly squeezed orange juice.",
      price: 2.99,
    },
    {
      title: "Lemonade",
      image: "assets/images/lemonade.jpg",
      description: "Refreshing lemonade.",
      price: 2.49,
    },
    {
      title: "Iced Tea",
      image: "assets/images/iced_tea.jpg",
      description: "Chilled iced tea.",
      price: 2.49,
    },
    {
      title: "Sprite",
      image: "assets/images/sprite.jpg",
      description: "Lemon-lime soda.",
      price: 1.99,
    },
    {
      title: "Fanta",
      image: "assets/images/fanta.jpg",
      description: "Orange flavored soda.",
      price: 1.99,
    },
    {
      title: "Root Beer",
      image: "assets/images/root_beer.jpg",
      description: "Classic root beer.",
      price: 2.49,
    },
    {
      title: "Energy Drink",
      image: "assets/images/energy_drink.jpg",
      description: "Boost your energy.",
      price: 3.49,
    },
  ],
  Sweets: [
    {
      title: "Chocolate Cake",
      image: "assets/images/chocolate_cake.jpg",
      description: "Rich and moist chocolate cake.",
      price: 4.99,
    },
    {
      title: "Apple Pie",
      image: "assets/images/apple_pie.jpg",
      description: "Classic apple pie with a flaky crust.",
      price: 3.99,
    },
    {
      title: "Ice Cream Sundae",
      image: "assets/images/ice_cream_sundae.jpg",
      description: "Delicious ice cream sundae with toppings.",
      price: 4.49,
    },
    {
      title: "Brownies",
      image: "assets/images/brownies.jpg",
      description: "Chewy and fudgy brownies.",
      price: 2.99,
    },
    {
      title: "Cheesecake",
      image: "assets/images/cheesecake.jpg",
      description: "Creamy and smooth cheesecake.",
      price: 4.99,
    },
    {
      title: "Cupcakes",
      image: "assets/images/cupcakes.jpg",
      description: "Assorted flavored cupcakes.",
      price: 3.49,
    },
    {
      title: "Donuts",
      image: "assets/images/donuts.jpg",
      description: "Freshly baked donuts with various toppings.",
      price: 1.99,
    },
    {
      title: "Pudding",
      image: "assets/images/pudding.jpg",
      description: "Creamy and delicious pudding.",
      price: 2.49,
    },
    {
      title: "Macarons",
      image: "assets/images/macarons.jpg",
      description: "Colorful and delicate macarons.",
      price: 3.99,
    },
    {
      title: "Fruit Tart",
      image: "assets/images/fruit_tart.jpg",
      description: "Fresh fruit tart with a buttery crust.",
      price: 4.49,
    },
  ],
  Sausages: [
    {
      title: "Bratwurst",
      image: "assets/images/bratwurst.jpg",
      description: "Traditional German sausage.",
      price: 5.99,
    },
    {
      title: "Chorizo",
      image: "assets/images/chorizo.jpg",
      description: "Spicy Spanish sausage.",
      price: 4.99,
    },
    {
      title: "Italian Sausage",
      image: "assets/images/italian_sausage.jpg",
      description: "Flavorful Italian sausage.",
      price: 5.49,
    },
    {
      title: "Andouille",
      image: "assets/images/andouille.jpg",
      description: "Smoked Cajun sausage.",
      price: 5.99,
    },
    {
      title: "Kielbasa",
      image: "assets/images/kielbasa.jpg",
      description: "Polish sausage with garlic flavor.",
      price: 4.99,
    },
    {
      title: "Breakfast Sausage",
      image: "assets/images/breakfast_sausage.jpg",
      description: "Savory breakfast sausage links.",
      price: 3.99,
    },
    {
      title: "Hot Dog",
      image: "assets/images/hot_dog.jpg",
      description: "Classic American hot dog.",
      price: 2.99,
    },
    {
      title: "Bockwurst",
      image: "assets/images/bockwurst.jpg",
      description: "German sausage made from veal and pork.",
      price: 5.49,
    },
    {
      title: "Merguez",
      image: "assets/images/merguez.jpg",
      description: "Spicy North African sausage.",
      price: 5.99,
    },
    {
      title: "Cumberland",
      image: "assets/images/cumberland.jpg",
      description: "Traditional British sausage.",
      price: 4.99,
    },
  ],
};

export default menuData;
